const colors = require('tailwindcss/colors');
const HUE = require('@mui/material/colors');

module.exports = {
    important: true,
    purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
    corePlugins: [
        'backgroundColor',
        'textColor',
        'preflight',
        'margin',
        'padding',
        'container',
        'alignContent',
        'alignItems',
        'alignSelf',
        'animation',
        'appearance',
        'backdropBlur',
        'backdropBrightness',
        'backdropContrast',
        'backdropFilter',
        'backdropGrayscale',
        'backdropHueRotate',
        'backdropInvert',
        'backdropOpacity',
        'backdropSaturate',
        'backdropSepia',
        'blur',
        'boxDecorationBreak',
        'boxShadow',
        'boxSizing',
        'brightness',
        'clear',
        'content',
        'contrast',
        'cursor',
        'display',
        'divideColor',
        'divideOpacity',
        'divideStyle',
        'divideWidth',
        'dropShadow',
        'fill',
        'filter',
        'flex',
        'flexDirection',
        'flexGrow',
        'flexShrink',
        'flexWrap',
        'float',
        'fontFamily',
        'fontSize',
        'fontSmoothing',
        'fontStyle',
        'fontVariantNumeric',
        'fontWeight',
        'gap',
        'gridAutoColumns',
        'gridAutoFlow',
        'gridAutoRows',
        'gridColumn',
        'gridColumnEnd',
        'gridColumnStart',
        'gridRow',
        'gridRowEnd',
        'gridRowStart',
        'gridTemplateColumns',
        'gridTemplateRows',
        'height',
        'hueRotate',
        'inset',
        'invert',
        'isolation',
        'justifyContent',
        'justifyItems',
        'justifySelf',
        'letterSpacing',
        'lineHeight',
        'listStylePosition',
        'listStyleType',
        'margin',
        'maxHeight',
        'maxWidth',
        'minHeight',
        'opacity',
        'objectFit',
        'mixBlendMode',
        'objectPosition',
        'order',
        'overflow',
        'overscrollBehavior',
        'padding',
        'position',
        'ringColor',
        'ringOffsetColor',
        'ringOffsetWidth',
        'ringOpacity',
        'ringWidth',
        'rotate',
        'scale',
        'skew',
        'space',
        'textAlign',
        'textOverflow',
        'textTransform',
        'transform',
        'transformOrigin',
        'transitionDelay',
        'transitionDuration',
        'transitionProperty',
        'transitionTimingFunction',
        'translate',
        'visibility',
        'whitespace',
        'width',
        'wordBreak',
        'zIndex',
        'borderRadius',
        'backgroundPosition',
        'backgroundRepeat',
        'backgroundSize',
        'accessibility',
        'borderWidth',
        'borderColor',
        'borderStyle'
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        screens: {
            sm: '600px',
            md: '960px',
            lg: '1280px',
            xl: '1920px',
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            gray: HUE.grey,
            red: HUE.red,
            yellow: HUE.yellow,
            green: HUE.green,
            blue: HUE.blue,
            indigo: HUE.indigo,
            purple: HUE.purple,
            pink: HUE.pink,
        },
    },
    variants: {
        extend: {},
    },
    plugins: [require('tailwindcss-rtl'), require('@tailwindcss/typography')],
};
